# ----------- CONFIGURABLE START -----------
title:            Idealist Careers - Expert tips, advice, and resources to help you find, land, love, and grow in your social-impact career.
description:      A blog from an expert in careers can help you to find new ways to revamp your resume, find a new job, break into a new industry, wow a recruiter or anything else career related that you need to know.
url:              www.lunatest-3.com # Site url, without a slash at the end.
signoff:          "muan" # Your name
facebook_appid:   # APP ID for like button, remove from /_includes/share.html if unwanted.
google_analytics: # Set tracking, remove from /javascripts/basic.js if unwanted.
share:            false # Turn on twitter and facebook share buttons

links:
  - name:         Posts
    url:          /
    external:     false
  - name:         About me
    url:          /about
    external:     false
# ------------ CONFIGURABLE END ------------

permalink:        /posts/:title
defaults:
  - values:
      layout: "default"
